debug: false

lobby:
  disabled-breaking:
    enabled: true
    ignore-creative: true
    worlds:
      - lobby
      - lobby_net
  spawn-location:
  on-auth:
    sound:
      enabled: true
      name: ENTITY_PLAYER_LEVELUP
      volume: 1.0
      pitch: 1.0
    message:
      - "§eWelcome!"