debug: false

server-type: UNKNOWN

anti-block-break:
  disabled: true
  ignore-creative: true
  whitelisted-worlds:
    - lobby
    - lobby_end

on-join:
  inform-player-about-autologin: true
  sound:
    ==: ConfigSound
    enabled: true
    name: ENTITY_PLAYER_LEVELUP
    volume: 1.0
    pitch: 1.0
  message:
    ==: ConfigMessage
    enabled: true
    content:
      - "§eWelcome join!"
  spawn-location:

on-auth:
  sound:
    ==: ConfigSound
    enabled: true
    name: ENTITY_PLAYER_LEVELUP
    volume: 1.0
    pitch: 1.0
  message:
    ==: ConfigMessage
    enabled: true
    content:
      - "§eWelcome auth!"
  move-to-server:
    enabled: false
    server-name: "lobby"

scoreboard:
  ==: ConfigScoreboard
  enabled: true
  title: "§eSurvival"
  lines:
    - "First line"
    - "Second line"
    - "poggers!"

economy:
  enabled: false
  currency: CZK

chat:
  enabled: true
  style: "{rank} §8| {name} §8» §r{message}"

misc:
  discord-invite-link: https://discord.gg/HpPJHtPE3t
  disable-interactions:
    ==: ConfigDisableInteraction
    enabled: false
    ignore-creative: true
    list-type: WHITELIST
    entries:
      - "wooden_button"
      - "any:door"